package com.example.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class ResultX(
    @Json(name = "address_components")
    val addressComponents: List<AddressComponent>?,
    @Json(name = "adr_address")
    val adrAddress: String?,
    @Json(name = "business_status")
    val businessStatus: String?,
    @Json(name = "current_opening_hours")
    val currentOpeningHours: CurrentOpeningHours?,
    @Json(name = "delivery")
    val delivery: Boolean?,
    @Json(name = "dine_in")
    val dineIn: Boolean?,
    @Json(name = "editorial_summary")
    val editorialSummary: EditorialSummary?,
    @Json(name = "formatted_address")
    val formattedAddress: String?,
    @Json(name = "formatted_phone_number")
    val formattedPhoneNumber: String?,
    @Json(name = "geometry")
    val geometry: GeometryX?,
    @Json(name = "icon")
    val icon: String?,
    @Json(name = "icon_background_color")
    val iconBackgroundColor: String?,
    @Json(name = "icon_mask_base_uri")
    val iconMaskBaseUri: String?,
    @Json(name = "international_phone_number")
    val internationalPhoneNumber: String?,
    @Json(name = "name")
    val name: String?,
    @Json(name = "opening_hours")
    val openingHours: OpeningHoursX?,
    @Json(name = "photos")
    val photos: List<PhotoX>?,
    @Json(name = "place_id")
    val placeId: String?,
    @Json(name = "plus_code")
    val plusCode: PlusCodeX?,
    @Json(name = "price_level")
    val priceLevel: Int?,
    @Json(name = "rating")
    val rating: Double?,
    @Json(name = "reference")
    val reference: String?,
    @Json(name = "reservable")
    val reservable: Boolean?,
    @Json(name = "reviews")
    val reviews: List<Review>?,
    @Json(name = "serves_beer")
    val servesBeer: Boolean?,
    @Json(name = "serves_brunch")
    val servesBrunch: Boolean?,
    @Json(name = "serves_dinner")
    val servesDinner: Boolean?,
    @Json(name = "serves_lunch")
    val servesLunch: Boolean?,
    @Json(name = "serves_vegetarian_food")
    val servesVegetarianFood: Boolean?,
    @Json(name = "serves_wine")
    val servesWine: Boolean?,
    @Json(name = "takeout")
    val takeout: Boolean?,
    @Json(name = "types")
    val types: List<String>?,
    @Json(name = "url")
    val url: String?,
    @Json(name = "user_ratings_total")
    val userRatingsTotal: Int?,
    @Json(name = "utc_offset")
    val utcOffset: Int?,
    @Json(name = "vicinity")
    val vicinity: String?,
    @Json(name = "website")
    val website: String?,
    @Json(name = "wheelchair_accessible_entrance")
    val wheelchairAccessibleEntrance: Boolean?
)